version: "2"
services:
  app:
    container_name: simple-app
    build:
      context: ../
      dockerfile: deployments/app/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../app/app.py:/app/app.py 
    
